### ISSUE TITLE
TS2304: Cannot find name 'LokiCollection'

### ISSUE THREAD

**Issue by peppertech** [chybie/file-upload-hapi#1]
I've cloned this project and have followed the instruction in the README file, but I'm getting this error message when the tsc command is being run.  I'm not familiar with Loki so excuse the question if is a really simple solution.

utils.ts(15,62): error TS2304: Cannot find name 'LokiCollection'.

**Comment by DmytroSeredinov** [comment]
You'll need simple change: rename `LokiCollection` to `Loki.Collection`.
